### ISSUE TITLE
Megamenu>submenu configuration lost when item edited/added in Joomla main menu manager

### ISSUE THREAD

**Issue by codeeditor** [t3framework/t3#340]
Joomla! 3.3.3
t3_blank Default 2.1.1
T3 Framework 2.1.2

Steps to reproduce issue:
T3 Template Navigation config:
Navigation Style: megamenu
Menu: Main Menu

T3 Megamenu configuration:
Main menu items + 1 column submenu

Submenu item configuration:
1. Delete submenu items (T3 Megamenu configuration)
2. Add module as submenu (Joomla module type: menu (othermenu))
3. Now on the front-end module appear as submenu item on megamenu hover, no Joomla submenu items displays so it's correct.
4. Edit publishing status or add new item to main menu in Joomla menu manager and save
5. Submenu items will show again on website front-end ever if they was deleted before in T3 Megamenu configuration

System:
Database Version	5.5.38-0+wheezy1
Database Collation	utf8_general_ci
PHP Version	5.4.4-14+deb7u12
FPM/FastCGI

**Comment by vmindru** [comment]
Steps to reproduce the issue

This video was recorded for Joomla Art as well. 
https://youtu.be/XH-dzwYG-oU

1) Amend a submenu in a menu with MegaMenu, add 1 extra column. 
2) Open any menu that is part of the "menu" above and just click save.
3) The columns of submenu got overwritten.

Expected result

mm_config settings do not get overwritten

Actual result

mm_config settings :{\"rows\":[[{\"item\":157,\"width\":6},{\"item\":160,\"width\":6}]]},\"alignsub\":\"justify\"},\"item-151\":{\"sub\":{\"rows\":[[{\"item\":152,\"width\":12}]]}}} get's removed

System information 
Joomla: 3.4.3
Purity III: 1.1.5
T3: 2.5.0

**Comment by chrisjohnstone** [comment]
I'm seeing this behaviour too. In a nutshell, removing a column works in the megamenu menu item works but only temporarily. After doing some other work on the site, it reappears but I have no idea why.

**Comment by carlosqribeiro** [comment]
I'm having this problem too. If i change any joomla menu option, template looses all the settings.
I'm not using any special or odd caracters (like & or any other like).

I'm using:

Joomla 3:4.8 (fresh new)
Purity III: 1.1.5
T3: 2.5.2

**Comment by larnet** [comment]
Bug still exists. I think the problem is caused by national chars (in my case - polish, like ą, ż, ź etc) 

Unfortunatelly i have to stop using this component due to this bug.

Joomla 3.6
T3 BS3 Blank 2.2.2
PHP 5.4
