### ISSUE TITLE
Javascript error in t3 template manager

### ISSUE THREAD

**Issue by mort3za** [t3framework/t3#347]
This is the javascript error:
``Javascript
Uncaught SyntaxError: Unexpected token s
``
in `index.php?option=com_templates&view=style&layout=edit&id=18:1`
and another error is:
``Javascript
Uncaught TypeError: Cannot read property 'vals' of undefined 
``
in `layout.js:511`

These errors prevent users to save settings in template manager.

**Comment by blackmonster1102** [comment]
I have the same issue.
Uncaught SyntaxError: Unexpected token h ...

Uncaught TypeError: Cannot read property 'vals' of undefined in layout.js:511

**Comment by mort3za** [comment]
@blackmonster1102 Check your block templates (in template folder). delete block templates one by one and check if it solved. I think it's because of a php error or logical t3 error on those template files.

**Comment by triva911** [comment]
@mort3za thank you very much, this was helpful.

I removed custom block that I have created and everything works fine.
