### ISSUE TITLE
Megamenu vs Menu items order

### ISSUE THREAD

**Issue by Ilya-Zhulin** [t3framework/t3#349]
Good day everybody and thank to devs for their work!
I've changed an order of first-level-items of my menu in Joomla Admin Panel. It works, menu order is changed in Joomla admin. But in Megamenu settings panel it doesn't changed. So, I have old order on frontpage and I can't chage the order of menu first-level-items if current menu is T3 Megamenu.

Thanks in advance.

**Comment by khanhlh** [comment]
Megamenu setting doesn't maintain the item order. Please remember to refresh the megamenu configuration or close and reopen it after you change your menu item order.
