### ISSUE TITLE
Menu items category don´t show for "Registred"

### ISSUE THREAD

**Issue by ddpneu** [t3framework/t3#357]
Hello, 
I have in one menu category all items as "Registered" and inside this menu category I have Login form. 
If I log in the items don´t show even though their should. I found out that if I set in one item as "Public" or put inside Title of page something, everything is working right. All menu items even the Registered one are showed.

I recorded this issue on the video so I can send it you for downloading. But it must be a private cos my website aren´t still public. 

Thank you for helping to solve this problem.

**Comment by khanhlh** [comment]
You should update configuration for registered access. In template manager, click "Megamenu" to enter Megamenu configuration, then select "Registered" for "Access" to create configuration for registered level. After make your change, click save and you could get the menu work as expected.
