### ISSUE TITLE
Problem with mobile devices (images is too big)

### ISSUE THREAD

**Issue by balashoff** [t3framework/t3#364]
sky-sea-sun.com
or images used mavik thumbnail plugin

**Comment by JorgeGama** [comment]
Had a quick look at your website and I found some inline styles. 
![workspace 1_010](https://cloud.githubusercontent.com/assets/1596455/5753036/f50ec74e-9c4f-11e4-8ba7-154cded7ec61.png)

Remove those styles from your articles and see if that helps.
