### ISSUE TITLE
Link behind level0 menu items does not open

### ISSUE THREAD

**Issue by MGHollander** [t3framework/t3#368]
Hi,

I have a megamenu configured to open on hover so the level0 menuitems are clickable, but they don't work unless an underlying page is opened.

See www.bubbelsenjets.nl for an example. Menuitem "producten" has subitems.

Regards,
Marc

**Comment by robwent** [comment]
Seem to open fine for me

**Comment by khanhlh** [comment]
Update to latest version of T3, you should get the issue fixed.

**Comment by MGHollander** [comment]
Great! Thanks
