### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by Armagetron** [t3framework/t3#373]
Using the blank template (t3_bs3_blank) I cannot align images to the right side (t3_blank works). My article looks like this:
```html
<p style="text-align: left;"><img src="images/img1.jpg" alt="img1" /></p>
<p style="text-align: left;">description 1</p>
<p style="text-align: right;"><img src="images/img2.jpg" alt="img2" /></p>
<p style="text-align: right;">description 2</p>
```
The text alignment works fine. However, the second image is aligned to the left. Aligning it to the centre works. The article is displayed correctly when using a different template.

Using the Firefox developer tools, I haven't found any CSS rule that might be causing this behaviour though I am not an CSS expert. Is this an error in the t3_bs3_blank template?

**Comment by khanhlh** [comment]
Instead of using style="text-align: right" in parent tag, you should use property align in img. Eg:
<img src="images/img.jpg" align="right" />

**Comment by Armagetron** [comment]
I'm sorry but the image link is broken.

**Comment by Armagetron** [comment]
Ok, thanks.
