### ISSUE TITLE
Footer in home page (t3 bs3 blank template)

### ISSUE THREAD

**Issue by antonioaltamura** [t3framework/t3#387]
I have a strange issue, in home page the footer is contained in  a div with class "container t3-sl t3-sl-1".
the result is the footer doesn't have width:100% as I want, but width=size of .container (1170px in desktop view)

I think it's an easy to solve backend issue, but I can't figure it out..

Here the screenshots:
In home page
http://www.awesomescreenshot.com/image/146413/d49ad553d1a6406cbfdbf5a57c6059aa

on the other pages
http://www.awesomescreenshot.com/image/146416/b010aad513238036e731638d67d3c2bf

**Comment by trungch** [comment]
We can't view your screenshots, please update your screenshots. We will help you debug and solve this problem.

Regards,

**Comment by antonioaltamura** [comment]
thanks for help but after more than a year I can't even remember which website I was talking about.
You can close.
