### ISSUE TITLE
missing frontend module editing icon

### ISSUE THREAD

**Issue by farzad123** [t3framework/t3#391]
frontend module editing icon does not show on joomla 3.4.1... 
backend , mouse on over is module and ACL is ok ... 
Check it please

**Comment by derChristoph** [comment]
same thing on my joomla!

**Comment by derChristoph** [comment]
see here: http://www.t3-framework.org/discussions/icon-compatibility.html#reply-495
but i don't know how to "add them"...

**Comment by trungch** [comment]
Now it's working fine. Please check again
