### ISSUE TITLE
Can't register on t3-framework.org

### ISSUE THREAD

**Issue by oe-bayram** [t3framework/t3#393]
Hi, 
it's not possible to register at t3-framework.org.
Whenever I submit Register, I get the message SMTP connection failed
and with this username and email adress I can't try it again then because I get the message that I'm already registered.

Thanks

**Comment by oe-bayram** [comment]
I have to do some changes at the megamenu.tpl.php and the javascript file in the base-bs3/js/ folder but I want to override them, to avoid overrides after an update.
Could you please help me?

**Comment by joomlart** [comment]
Hi,

Could you please provide me your username that you registered in our t3 site, I will check and activate it for you.
About the override thing, please check out the detail documentation: http://www.t3-framework.org/documentation/new-features#isolate-template
Using "local" folder for any override so when you upgrade, your work will not be lost.

Regards.

**Comment by oe-bayram** [comment]
Hi,
but I don't want to override a layout. I want to override the files in the plugin core:
/plugins/system/t3/includes/menu/megamenu.tpl.php
and
/plugins/system/t3/base-bs3/js/menu.js

PS: my username, I registered at t3 is:
oebayram

Thanks

**Comment by joomlart** [comment]
Hi again,

Please refer to the documentation: http://www.t3-framework.org/documentation/extend-com-content#override-megamenu
It will show you steps to override megamenu.

Regards.
