### ISSUE TITLE
Tabs inside Mega Menu Drop Down

### ISSUE THREAD

**Issue by arunsasi** [t3framework/t3#405]
Hi,

Is it possible to integrate Tabs inside the T3 Mega Menu drop down. If i add as a module will it work.

For reference 
http://www.lynda.com/ (Browse Library)
http://wpmegamenu.com/ (Hover the The Works and Tabs Menu)

Thanks
Arun

**Comment by khanhlh** [comment]
To enable tab-style, select a column contains some menu items, enable option "Tab-style" in toolbox. Each menu items in this column will be a tab, its submenu (children menu items or module) is tab content.
