### ISSUE TITLE
Unwanted spaces

### ISSUE THREAD

**Issue by schipa** [t3framework/t3#406]
There are unwanted spaces in `/source/plg_system_t3/includes/menu/megamenu.tpl.php`.
"**Note. It is important to remove spaces between elements.**" is given but not maintained.

Line 274:
```php
return "<span class=\"$class\" $title $dropdown>$icon$title $linktype$caret$caption</span>";
                                                           ▲
```
and 292, 296, 300.

**Comment by khanhlh** [comment]
You should create a pull request to fix the issue.
