### ISSUE TITLE
Modals do not open in mega menu

### ISSUE THREAD

**Issue by betteryouthanme** [t3framework/t3#413]
I've created a module including a modal and puplished it into Mega Menu.
But on click nothing happens, the modal does not open.

![modal-menu](https://cloud.githubusercontent.com/assets/8537297/9131683/15a4b29a-3cee-11e5-86a2-2b38aade9650.gif)

In Kunena 4 Crypsis Bootstrap 3 template login/logout -popout menu, 
there's also a modal link which does not open. Same issue i guess.
![modal_kunena](https://cloud.githubusercontent.com/assets/8537297/9136105/366d4070-3d14-11e5-9401-0b942cdffb43.jpg)

**Comment by betteryouthanme** [comment]
have you been able to reproduce the issue? A little info would be kind ;)

**Comment by arunsasi** [comment]
Try below js (insert in in your script.js)

$('#your_object_id').click(function(e) {
				 $('#modal_id').modal('toggle');
			});

**Comment by betteryouthanme** [comment]
Thanks for your reply.

Where exactly i have to add the code?
Do i have to edit modal_id and your_object_id and if, where do i get the object ID?

**Comment by khanhlh** [comment]
Fixed in commit #286bb78bc2c3cceb166d6466979a5604e4954fb0
