### ISSUE TITLE
 Masthead Title/Slogan does not work with menu item alias

### ISSUE THREAD

**Issue by betteryouthanme** [t3framework/t3#419]

**Comment by khanhlh** [comment]
Cannot reproduce the issue.

**Comment by betteryouthanme** [comment]
Steps to reproduce:
1) Create a menu entry. Type: e.g Articles -> Single Article
2) Now create an alias menu entry refering to the entry in step 1
3) Fill in Masthead Title and slogan in tab: Page Display
4) on frontend select the alias menu entry
Result: No slogan/title shown, neither the one from alias menu nor single article menu entry
