### ISSUE TITLE
White space is appearing between the menu name and caret.

### ISSUE THREAD

**Issue by arunsasi** [t3framework/t3#422]
There is a white space is appearing between the menu name and caret. this is not happening for all drop down menu.

For example http://www.joomlart.com/demo/#ja_events-ii

Drop down menu HOME is appering with a white space after the text.
"Home "

But drop down menu OTHER is appering with a white space before the text.
" Other"

How can i remove the white space

Thanks
Arun

**Comment by khanhlh** [comment]
Reported in issue #406
