### ISSUE TITLE
T3 Mega menu Add/Remove Column reset after adding new menu

### ISSUE THREAD

**Issue by arunsasi** [t3framework/t3#425]
I have a parent & child menu list, which i have removed its column. When i add new menu item in Joomla main menu all the removed column resets.

![t3](https://cloud.githubusercontent.com/assets/270789/11087712/994a249c-8882-11e5-9bf8-000d55cffeba.png)

**Comment by robwent** [comment]
I've been seeing the same thing.

In mm, the normal dropdowns are removed with the column buttons and custom modules are added for the dropdown content.
When a menu item is changed, the removed columns then reappear in the menu and you have to go back to the menu settings and remove the column again.

**Comment by arunsasi** [comment]
Hi All,

Any solution for this issue.
