### ISSUE TITLE
Duplicate plugins/system/t3/plugins/system/t3 in path for glyphicons-halflings

### ISSUE THREAD

**Issue by markovanderpuil** [t3framework/t3#428]
When I use a glyphicons halflings icon in my own module the T3 adds and extra *plugins/system/t3/* to the path of the font resulting in 404 errors and glyphicons not working anymore.

Safari error log:

    http://example.com/plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.woff [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (glyphicons-halflings-regular.woff, line 0)
    http://example.com/plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.ttf [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (glyphicons-halflings-regular.ttf, line 0)
    http://example.com/plugins/system/t3/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (glyphicons-halflings-regular.svg, line 0)

The correct fonts are at:

    http://example.com/plugins/system/t3/base-bs3/bootstrap/fonts/glyphicons-halflings-regular.woff

I have a workaround in place for apache using Alias:

    Alias /plugins/system/t3/plugins/system/t3/ /opt/joomla/joomla-site/public_html/plugins/system/t3/

But I'm not able to do that on every server that wants to use my module later.

Any idea which file is causing this?

**Comment by daistahara** [comment]
+1

**Comment by max-sixblade** [comment]
+1000, anyone?

**Comment by khanhlh** [comment]
Please confirm if the issue is solved.
