### ISSUE TITLE
Problem with Joomla 3.6

### ISSUE THREAD

**Issue by massirock** [t3framework/t3#442]
T3 framework version 2.5.5 have a problem with Joomla 3.6 multilanguage.
Isn't possible configure the layout. 

![2016-07-19_160504](https://cloud.githubusercontent.com/assets/20539541/16952731/bc94f07c-4dca-11e6-9474-dafd04e08879.png)

**Comment by khanhlh** [comment]
Please check if you have .htaccess file inside your root folder. Or you can disable rewrite in sef configuration.
