### ISSUE TITLE
Position on Front-end

### ISSUE THREAD

**Issue by Edward0625** [t3framework/t3#448]
Hi!

In front-end i want to change the position from a module, but the list is empty.
![1](https://cloud.githubusercontent.com/assets/7513278/19562438/9bcb9070-96dc-11e6-8b6a-28a6e34289b6.jpg)
Template T3 BS3

If i select default template is Protostar, the position is listed.
![2](https://cloud.githubusercontent.com/assets/7513278/19562646/5a630108-96dd-11e6-9420-4868e2f0b078.jpg)

Thank you, Edmond

**Comment by Grandement** [comment]
I have the same problem. Does anyone know, how to fix it?
