### ISSUE TITLE
Langauge switching proble with T3 framework

### ISSUE THREAD

**Issue by ismaelhaider** [t3framework/t3#472]
hello,
I am using Jomsocial +socialize+T3 framework, Ithere is problem when switching from 1 Language to other, Its not switching properly, I ask  developer and they said there is problem with T3 Framework, 
<html lang="<?php echo $this->language; ?>" dir="<?php echo $this->direction; ?>"
In URL its change the link to EN or AR but in code its not changing, after refresh page then its showing correct langauge.check the video 
http://screencast-o-matic.com/watch/cbht2GX5U5

**Comment by sinisakrisan** [comment]
Hi @ismaelhaider

If you use Joomla 3.7, there might be an issue with some old and obsolete translations explained here https://www.jomsocial.com/blog/j37-translations

Please try to apply fixes from above blog post to your language files. 
If that don't work, please contact our support at https://jomsocial.com/forum
