### ISSUE TITLE
EDITOR – EXTRA FIELDS tab is missing after upgrade T3 plugin v2.6.5

### ISSUE THREAD

**Issue by honglt** [t3framework/t3#475]
Test on purity iii and plg_system_t3.v2.6.4 installed => Edit an article on the frontend >> Extra fields menu tab is still there
- Upgrade T3 v2.6.5 >> extra fields menu tab is gone
![tab](https://user-images.githubusercontent.com/10841664/26924529-765740b0-4c70-11e7-92b2-034379536d60.png)

**Comment by joomlart** [comment]
Fixed
