### ISSUE TITLE
Missing editor window tabs after upgrading to t3 framework plugin v2.6.5

### ISSUE THREAD

**Issue by wnkkm** [t3framework/t3#476]
After upgrading to v2.6.5 of t3 framework plugin, the editing window's tabs of "Editor / Extra Fields / Publishing / Language / Metadata" were missing (not displayed).  I had to go back to the previous version v2.6.4 of t3 framework plugin to resolve this issue.

My system info: Joomla 3.7.2, PHP 7.0, Purity III v1.2.0

Thanks.

Wonkoo

**Comment by Matthias02** [comment]
The same problem I've got too.
In backend everything is all right, but in the frontend the tabs are not shown.
On console the following message is thrown: "TypeError: document.formvalidator is null"  which references to following code:
`Joomla.submitbutton = function(task)
	{
		if (task == 'article.cancel' || document.formvalidator.isValid(document.getElementById('adminForm')))
		{
			WFEditor.getContent('jform_articletext');
			Joomla.submitform(task);
		}
	}`

**Comment by wnkkm** [comment]
This issue has been fixed with t3 framework plugin v2.6.6.

Thanks.

Wonkoo
