### ISSUE TITLE
Highlighting search results on Joomla 3.7.3 using T3 BS3 Blank Template

### ISSUE THREAD

**Issue by inscriptios** [t3framework/t3#479]
After updating to Joomla! 3.7.3 there are problems with displaying search results. Now searched word is not highlighted, instead of that code is shown:

`<span class="highlight">searched_word</span>`

![- - mozilla firefox 2017-07-10 21 36 12](https://user-images.githubusercontent.com/5901987/28033789-01813e6a-65b8-11e7-8470-d26f21b73a65.png)

There is no any problem when using default Joomla! 3.7.3 front-end template. There is no any problem when using Joomla! 3.7.2. I'm using the latest version of T3 Framework plugin (2.6.5) and T3 BS3 Blank Template (2.2.6).

**Comment by trungch** [comment]
Fixed
