### ISSUE TITLE
com_fields output is hosed on a T3 template

### ISSUE THREAD

**Issue by stutteringp0et** [t3framework/t3#494]
Working with com_fields and user accounts, I found that displaying a profile (or contact associated with that user) displays each of the fields as a plain text value.  Switching to beez or protostar I get the field formatting back.  

It occurs to me that the field output is found in plugins/system/fields/FIELDPLUGIN/tmpl/FIELDPLUGIN.php - so something within T3 is overriding that tmpl output for all fields.

I haven't had a chance to really look at it closely, so this is just my initial report.

**Comment by joomlart** [comment]
It was fixed already
