### ISSUE TITLE
Notice: Trying to get property of non-object  in T3 plugin ver. 2.7.0

### ISSUE THREAD

**Issue by MarHaj** [t3framework/t3#509]
When editing Joomla! 3.8.1 content in backend there are two system messages:

- **Notice**: Trying to get property of non-object in website\plugins\system\t3\includes\core\bot.php on line 409
- **Notice**: Trying to get property of non-object in website\plugins\system\t3\includes\core\bot.php on line 412

**Comment by sisiwak** [comment]
I have the same problem after version 3.8.2 update

**Comment by MarHaj** [comment]
**The same for me**: Joomla! 3.8.2 + T3 system plugin 2.7.0

**Comment by MarHaj** [comment]
The same for me: Joomla! 3.8.2 + T3 system plugin 2.7.0

**Comment by yanliom** [comment]
Same for me: Joomla 3.8.5
