### ISSUE TITLE
No highlighted menu item in sidebar menu module box with T3 2.7.0

### ISSUE THREAD

**Issue by wnkkm** [t3framework/t3#511]
Hi,

The current active menu item in a sidebar menu module box was not highlighted any more after upgraded T3 system plugin from 2.6.7 to 2.7.0.

So I had to add the following CSS rule in my custom.css file in my template/css folder:

.t3-sidebar .nav > li.active > a { /* Highlight the active menu item in sidebar menu module box */
    color: #ffffff;
    background-color: #0077bb;
}

I think bootstrap.css of T3 2.7.0 had some missing/incorrect rule. 
I had rebuilt my local bootstrap.css from less file. I hope less file be corrected in a next T3 plugin release.

Thanks.

Wonkoo

**Comment by trungch** [comment]
This issue has fixed in T3 Framework 2.7.1. Please update the latest version, provide us your site url if that issue still appear on your site.
