### ISSUE TITLE
Menu class suffix name merged to module-ct ul class

### ISSUE THREAD

**Issue by Stefanxxx** [t3framework/t3#514]
Hello,

After updating to the latest t3 framework (running t3_bs3_blank), the ul class in the "module-ct" div merges the menu class name with the "menu" class.
Instead of "nav **menu** **mycustomclass**" it makes it "nav **menumycustomclass**".
Managed to work around this by adding a blank space before the menu class suffix, from the joomla module settings.

Also shown:
![bs3_error](https://user-images.githubusercontent.com/34322309/33689578-b721ede6-dae8-11e7-9742-cd88cb813908.PNG)

Confirmed the issue in joomla 3.7.5 and 3.8.2. Running latest PHP 7.2 and MariaDB 10.2

**Comment by trungch** [comment]
It's working fine. You need add space before the menu class suffix. Update the T3 latest version if that issue still appears on your site.
