### ISSUE TITLE
T3 Logo does not show on webpage using Purity III template

### ISSUE THREAD

**Issue by pierre-pvln** [t3framework/t3#519]
If I enable the "Show T3 logo" in the "General" tab of Purity III template i get 2 errors:

1) the logo which should be present at  
http://joomlart.s3.amazonaws.com/images/jat3v3-documents/logo-complete/t3logo-big-color.png
does not show on the webite.
Furthermore if i put this link directly in my firefox browser it generates an XML file.

2) because my site is https based the usage of http://joomlart.s3.amazonaws.com/images/jat3v3-documents/logo-complete/t3logo-big-color.png leads to a security issue in firefox since it generates mxed content.

**Comment by trungch** [comment]
Fixed and updated to the in the Purity iii package.
