### ISSUE TITLE
T3 2.7.1 span class="element-invisible" Empty appears on all article pages

### ISSUE THREAD

**Issue by DrZen33** [t3framework/t3#524]
Hi everyone
Long time Joomla and T3 user here.
An extra element started to appear on all my article pages, after I updated T3 to version 2.7.1
I have been using T3 with the same Template design for many years now and have never seen this problem before.

Below is a screen shot showing the problem on live website.
On each article page, I have a cog/button that reveals the Print and Email links.
There should only be a cog and arrow visible.

After installing T3 2.7.1, the word **Empty** appears next to the cog/button.
When I check **view-source** for all article pages, there is an extra span class that has been added and the word **Empty**.

The additional code is this.
*I have replaced normal brackets with [ ] brackets.
[span class="element-invisible"]Empty[/span]

Is there a problem with T3 2.7.1 and/or how can I remove this unwanted element ?

![t3-2 7 1-empty-element-1](https://user-images.githubusercontent.com/20509046/40039389-996cb116-5859-11e8-91e7-4ace0f20c7b7.png)

Regards
Derek

**Comment by trungch** [comment]
Hi,
Add the bellow CSS rules to the custom.css file and copy that file to the css folder of the current joomla template.
`.element-invisible { display: none; }`

**Comment by DrZen33** [comment]
Thank you for that easy solution and taking the time to answer.
I really do appreciate this :)

Cheers 👍
