### ISSUE TITLE
Can't access T3 templates in com_templates: Cannot use object of type TemplatesViewStyle as array

### ISSUE THREAD

**Issue by TiepiNL** [t3framework/t3#569]
I can't edit my T3 template settings in the administrator console anymore. I can still access the configuration page for non-t3 templates, but clicking a T3 template results in an error.: "Cannot use object of type TemplatesViewStyle as array" I don't know if it's caused by the recent T3 plugin update, or by the Joomla 3.10.0 or 3.10.1 update.

[Thu Aug 26 00:04:22.507302 2021] [proxy_fcgi:error] [pid 23447:tid 139760080717568] [client xxxxxxxxxxx] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: class_sfx in /xxxxxxxx/plugins/system/t3/base-bs3/html/mod_menu/default.php on line 21PHP message: PHP Notice:  Undefined variable: list in /xxxxxxxxxx/plugins/system/t3/base-bs3/html/mod_menu/default.php on line 22PHP message: PHP Warning:  Invalid argument supplied for foreach() in /xxxxxxxxxx/plugins/system/t3/base-bs3/html/mod_menu/default.php on line 22', referer: https://www.jacobsmeubels.nl/administrator/index.php?option=com_templates

![image](https://user-images.githubusercontent.com/7967223/130870982-22e6bf89-e893-4341-aaa9-5aa61052b239.png)

Also, I had some custom google analytics code configured, which isn't loaded on my site anymore.

**Comment by TiepiNL** [comment]
I uninstalled the T3 System Plugin and installed the 3.0.2 again. This solved the issue.

**Comment by micker** [comment]
for me same error on 3.0.4
