### ISSUE TITLE
missing module titles when placed with loadposition in article since T3 system plugin version 3.0.0 up to current 3.0.3

### ISSUE THREAD

**Issue by level420** [t3framework/t3#572]
running joomla 3.10.1 with T3 system plugin version 3.0.3.

We recently updated the T3 system plugin from version 2.7.7 to version 3.0.3 and observed that modules placed with loadposition in articles to not show the module titles anymore.

Downgrading the T3 system plugin to 2.7.7 brought us the module titles back. 
Updating to version 3.0.0 showed the faulty behavior again.

What happens is that the usual envelope with
```
<div class="moduletable">
...
</div>
```
and thus also the herein rendered title element `h3` is missing.

We use the `loadposition` macro in articles a lot. This bug destroys our layout on several websites.

**Comment by level420** [comment]
tracked the problem down to method `renderModule` in https://github.com/t3framework/t3/blob/master/source/plg_system_t3/includes/joomla4/ModuleHelper.php#L42 where modules which are loaded via `loadposition` do have the original module style `xhtml` in ```$attribs['style']```, but modules which are loaded at "official" template positions have `T3Xhtml` as module style.

**Comment by kienduongbk** [comment]
Yes, you're right @level420.
 I'll fix it in the next release.

**Comment by level420** [comment]
@kienduongbk thank you for the fast fix! we'll test the new version and report back.
